//! Raw FFI bindings to the ONNX Runtime plugin-EP C ABI, plus the version gate.
//!
//! # Why bindgen and not hand-written bindings
//!
//! The plugin-EP ABI is a set of C structs whose fields are function pointers. Getting a field's
//! *order* wrong does not fail to compile and does not fail to load — it calls the wrong function
//! pointer with the wrong argument types, which is undefined behaviour with a plausible-looking
//! stack trace somewhere else entirely. `OrtApi` alone carries several hundred entries and grows
//! every ORT release; `OrtEp` and `OrtEpFactory` each gained fields in 1.23, 1.24 and 1.28.
//! Transcribing that by hand, repeatedly, against an API that is still explicitly experimental, is
//! a silent-UB factory. bindgen derives the layout from the same bytes the ORT binary was compiled
//! from, so field order is correct by construction and an upstream reshuffle produces a *compile*
//! error at our call sites rather than a runtime miscall.
//!
//! The usual argument against bindgen — "it needs libclang on every build machine" — is paid once,
//! in CI provisioning, and is the same bet `onnxruntime-mlx` already makes successfully. The usual
//! argument *for* hand-written bindings — "the surface is small and stable" — is exactly the
//! premise that does not hold here.
//!
//! What we do take from the hand-written camp: the headers are **vendored and version-pinned**
//! (`third_party/onnxruntime/include`, ORT `v1.28.0`, commit `da9b5e36`), so the bindings are
//! reproducible byte-for-byte and an ORT bump is a reviewable diff rather than whatever happened
//! to be in `$ORT_HOME` on the build machine. See `third_party/onnxruntime/PROVENANCE.md`.
//!
//! # Version gate
//!
//! Three numbers, and they mean different things:
//!
//! * [`ORT_API_VERSION_EXPECTED`] (28) — what we are **compiled** against, and what we ship
//!   against. A compile-time assertion ties it to the vendored headers.
//! * [`ORT_API_VERSION_MIN`] (24) — the oldest host we will **run** against.
//! * [`NegotiatedApi::version`] — what the host in front of us actually serves, resolved at load
//!   time by [`check_api_version`].
//!
//! `OrtApi`, `OrtEp` and `OrtEpFactory` are append-only: version *v* is a prefix of version 28.
//! That makes it safe to run on an older host **provided we never touch a field added after
//! *v***, which is not a promise a comment can keep. So [`NegotiatedApi::supports`] is a real
//! gate, and every optional entry point has a `since::*` constant naming the version that
//! introduced it. ORT itself does exactly this on its side of the boundary — see the
//! `ort_version_supported < 24` guard around `CreateExternalResourceImporterForDevice` in
//! `ep_factory_provider_bridge.h`.
//!
//! Below [`ORT_API_VERSION_MIN`] we refuse to load, loudly, rather than populate a 28-shaped
//! vtable for a host that will read it with a differently-shaped header.

/// Generated by `build.rs` with bindgen from the vendored ORT headers.
///
/// This module is the *only* place raw ORT ABI types are defined, and it is `pub(crate)` so they
/// cannot escape the crate. Layering rule 1 (`DESIGN.md` §4.2) forbids anything under `src/ops/`
/// from naming a type from here; `tests/layering.rs` enforces that mechanically.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all,
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks
)]
pub mod ort {
    include!(concat!(env!("OUT_DIR"), "/ort.rs"));
}

use std::ffi::CStr;

/// The ORT plugin-EP C ABI version this crate is built against.
///
/// Pinned to ORT **1.28.0** (`ORT_API_VERSION` = 28), which is the version whose headers are
/// vendored in `third_party/onnxruntime/include`. Bumping this requires re-vendoring the headers
/// and bumping `[package] version` to `0.<this>.0` — the crate version scheme is
/// `0.<ORT_API_VERSION>.<patch>` precisely so a user can read ABI compatibility off the version
/// string (`DESIGN.md` §3.1).
///
/// 1.28 specifically (per the Fact Checker's verification, 2026-07-28): 1.27 has a null-allocator
/// bug in plugin-EP `PrePack` that would bite us, fixed in 1.28.
pub const ORT_API_VERSION_EXPECTED: u32 = 28;

/// The oldest host ABI version this EP will run against: ORT **1.24**.
///
/// `OrtEpFactory` has existed since 1.22, but 1.24 is where the plugin-EP surface we depend on
/// settled — it is the release that added `CreateExternalResourceImporterForDevice`, and ORT's own
/// bridge uses `ort_version_supported < 24` as its compatibility line. Declaring 24 rather than 22
/// means we never have to reason about the 1.22/1.23 factory layouts at all.
///
/// Running below [`ORT_API_VERSION_EXPECTED`] is safe only because `OrtApi`, `OrtEp` and
/// `OrtEpFactory` are append-only, so an older host's layout is a prefix of ours. The obligation
/// that creates — never call a field the host does not have — is discharged by
/// [`NegotiatedApi::supports`] plus the [`since`] constants, not by hoping.
pub const ORT_API_VERSION_MIN: u32 = 24;

/// The ORT version that introduced each optional entry point we care about.
///
/// Every conditional use of the ABI is gated on one of these via [`NegotiatedApi::supports`], so
/// "is this available?" is answered by a named constant with a citation rather than by a guess at
/// the call site.
pub mod since {
    /// `OrtEpFactory::CreateExternalResourceImporterForDevice` — ORT 1.24.
    ///
    /// Note the symbol name: `CreateExternalResourceImporterForDevice`, **not**
    /// `...ForDeviceImpl`. The `Impl`-suffixed name appears only as a local static inside ORT's
    /// own example/test code and is not public API (verified 2026-07-28). The EP-side vtable we
    /// would populate is `OrtExternalResourceImporterImpl`; the caller-side counterpart lives on
    /// `OrtInteropApi`.
    pub const EXTERNAL_RESOURCE_IMPORTER: u32 = 24;

    /// Every constant in this module, for the test that checks they all sit inside the supported
    /// version window. Add new entries here as well as above — a `since::*` that nothing checks is
    /// how a gate silently becomes decoration.
    pub const ALL: &[(&str, u32)] = &[("EXTERNAL_RESOURCE_IMPORTER", EXTERNAL_RESOURCE_IMPORTER)];
}

// Compile-time gate: if someone re-vendors headers from a different ORT release without updating
// `ORT_API_VERSION_EXPECTED`, this fails the build. It cannot become a runtime surprise.
const _: () = assert!(
    ORT_API_VERSION_MIN <= ORT_API_VERSION_EXPECTED,
    "the minimum supported ORT ABI cannot exceed the one we compile against"
);
const _: () = assert!(
    ort::ORT_API_VERSION == ORT_API_VERSION_EXPECTED,
    "The vendored ONNX Runtime headers declare a different ORT_API_VERSION than \
     ORT_API_VERSION_EXPECTED. Update ORT_API_VERSION_EXPECTED in src/sys.rs, bump [package] \
     version to 0.<ORT_API_VERSION>.0 in Cargo.toml, and refresh \
     third_party/onnxruntime/PROVENANCE.md."
);

// The crate version must encode the ABI version it is compiled against (`DESIGN.md` §3.1). This
// keeps `GetVersion` (which reports CARGO_PKG_VERSION verbatim) honest without a runtime check.
const _: () = {
    let major = env!("CARGO_PKG_VERSION_MAJOR").as_bytes();
    let minor = env!("CARGO_PKG_VERSION_MINOR").as_bytes();
    assert!(
        major.len() == 1 && major[0] == b'0',
        "crate version must be 0.<ORT_API_VERSION>.<patch>"
    );
    assert!(
        minor.len() == 2 && minor[0] == b'2' && minor[1] == b'8',
        "crate version minor must equal ORT_API_VERSION_EXPECTED (28)"
    );
};

/// Outcome of the load-time ABI negotiation performed in `CreateEpFactories`.
#[derive(Debug)]
pub struct NegotiatedApi {
    /// The `OrtApi` table for [`NegotiatedApi::version`]. Never null.
    pub api: *const ort::OrtApi,
    /// The plugin-EP sub-API. Never null.
    pub ep_api: *const ort::OrtEpApi,
    /// The ABI version the host actually served — between [`ORT_API_VERSION_MIN`] and
    /// [`ORT_API_VERSION_EXPECTED`] inclusive.
    ///
    /// This is the value written into `OrtEpFactory::ort_version_supported` and
    /// `OrtEp::ort_version_supported`, so ORT reads exactly as much of our vtables as it
    /// understands, and never a field it would interpret with a different layout.
    pub version: u32,
}

impl NegotiatedApi {
    /// Is an entry point introduced in ORT ABI version `since` available on this host?
    ///
    /// Use with a named constant from [`since`], never a bare integer:
    ///
    /// ```ignore
    /// if negotiated.supports(sys::since::EXTERNAL_RESOURCE_IMPORTER) { /* populate the slot */ }
    /// ```
    #[inline]
    #[must_use]
    pub fn supports(&self, since: u32) -> bool {
        self.version >= since
    }
}

/// Negotiate the ORT API version with the host.
///
/// Asks for [`ORT_API_VERSION_EXPECTED`] first and walks down to [`ORT_API_VERSION_MIN`], taking
/// the first version the host serves. Returns `Err(message)` if the host cannot serve any of them;
/// the caller turns the message into an `OrtStatus` (it needs a status-capable `OrtApi` to do so,
/// which is why this function does not build the status itself).
///
/// Walking down is safe *only* because `OrtApi`, `OrtEp` and `OrtEpFactory` are append-only, so an
/// older version's layout is a prefix of the one our vendored headers describe. Two things make
/// that safety real rather than assumed: we report the negotiated version back to ORT in
/// `ort_version_supported` (so ORT stops reading our vtables where its own knowledge stops), and
/// every field we populate that was added after [`ORT_API_VERSION_MIN`] is gated on
/// [`NegotiatedApi::supports`].
///
/// We stop at [`ORT_API_VERSION_MIN`] rather than probing all the way down. Below that the factory
/// layout is one we have never validated, and populating a 28-shaped struct for it would put our
/// function pointers in slots ORT reads as something else.
///
/// # Safety
/// `ort_api_base` must be a valid, non-null `OrtApiBase` as supplied by ORT to
/// `CreateEpFactories`, and must remain valid for the lifetime of the returned pointers.
pub unsafe fn check_api_version(
    ort_api_base: *const ort::OrtApiBase,
) -> Result<NegotiatedApi, String> {
    if ort_api_base.is_null() {
        return Err("ONNX Runtime passed a null OrtApiBase to CreateEpFactories".to_string());
    }

    // SAFETY: the caller guarantees `ort_api_base` points at a live `OrtApiBase`. Both members are
    // populated by ORT for every version of the ABI that has ever existed, but we still treat the
    // function pointers as `Option` (bindgen models them that way) and refuse to unwrap blindly.
    let (get_api, get_version_string) = unsafe { ((*ort_api_base).GetApi, (*ort_api_base).GetVersionString) };

    let Some(get_api) = get_api else {
        return Err("OrtApiBase::GetApi is null; this host is not a usable ONNX Runtime".to_string());
    };

    let host_version = match get_version_string {
        // SAFETY: `get_version_string` is a plain `const char*` getter with no arguments; ORT
        // returns a pointer to a static string with process lifetime, so reading it here cannot
        // outlive its allocation. Treated as best-effort diagnostics only.
        Some(f) => unsafe {
            let p = f();
            if p.is_null() {
                "<unknown>".to_string()
            } else {
                CStr::from_ptr(p).to_string_lossy().into_owned()
            }
        },
        None => "<unknown>".to_string(),
    };

    let mut negotiated: Option<(*const ort::OrtApi, u32)> = None;
    let mut candidate = ORT_API_VERSION_EXPECTED;
    while candidate >= ORT_API_VERSION_MIN {
        // SAFETY: `get_api` is ORT's version dispatcher; it returns either a valid `OrtApi` for
        // the requested version or null. Passing any u32 is well-defined and has no side effects.
        let api = unsafe { get_api(candidate) };
        if !api.is_null() {
            negotiated = Some((api, candidate));
            break;
        }
        candidate -= 1;
    }

    let Some((api, version)) = negotiated else {
        return Err(format!(
            "VulkanExecutionProvider requires ONNX Runtime with ORT_API_VERSION >= \
             {ORT_API_VERSION_MIN} (ONNX Runtime 1.{ORT_API_VERSION_MIN}+; built and tested \
             against 1.{ORT_API_VERSION_EXPECTED}). This host reports version {host_version} and \
             refused GetApi() for every version from {ORT_API_VERSION_EXPECTED} down to \
             {ORT_API_VERSION_MIN}. Refusing to load rather than call into a differently-shaped \
             plugin-EP vtable."
        ));
    };

    // SAFETY: `api` is non-null and points at ORT's static `OrtApi` table for `version`, in which
    // `GetEpApi` is present (it has existed since 1.22 and `version >= 24`).
    let ep_api = unsafe {
        match (*api).GetEpApi {
            Some(f) => f(),
            None => std::ptr::null(),
        }
    };
    if ep_api.is_null() {
        return Err(format!(
            "ONNX Runtime {host_version} returned an OrtApi for version {version} but no \
             OrtEpApi; the plugin-EP surface is unavailable."
        ));
    }

    Ok(NegotiatedApi { api, ep_api, version })
}

/// Release a non-null `OrtStatus` we own.
///
/// The `OrtApi` allocates a status object the caller owns even for benign "not found" /
/// "buffer too small" results, so every ignored status must be released or it leaks.
///
/// # Safety
/// `api` must be a live `OrtApi`; `status` must be null or a status this thread owns.
#[inline]
pub unsafe fn release_status(api: *const ort::OrtApi, status: *mut ort::OrtStatus) {
    if api.is_null() || status.is_null() {
        return;
    }
    // SAFETY: caller guarantees `api` is live and `status` is an owned, not-yet-released status.
    unsafe {
        if let Some(release) = (*api).ReleaseStatus {
            release(status);
        }
    }
}

/// Build an `OrtStatus` from an error code and a message.
///
/// Returns null if `api` is null (nothing else is possible — a status can only be allocated by
/// ORT) or if the message cannot be represented as a C string.
///
/// # Safety
/// `api` must be null or a live `OrtApi`.
pub unsafe fn make_status(
    api: *const ort::OrtApi,
    code: ort::OrtErrorCode,
    message: &str,
) -> *mut ort::OrtStatus {
    if api.is_null() {
        return std::ptr::null_mut();
    }
    // Interior nul bytes cannot be sent through a C string; replace rather than drop the error.
    let sanitized = message.replace('\0', "?");
    let Ok(c) = std::ffi::CString::new(sanitized) else {
        return std::ptr::null_mut();
    };
    // SAFETY: `api` is live per the caller; `CreateStatus` copies the message, so `c` may be
    // dropped as soon as the call returns.
    unsafe {
        match (*api).CreateStatus {
            Some(f) => f(code, c.as_ptr()),
            None => std::ptr::null_mut(),
        }
    }
}

// -------------------------------------------------------------------------------------------
// The external-resource-importer seam (zero-copy IO binding). NOT implemented in M0.
//
// # What it is
//
// An OS-handle-based external memory import path, added in ORT **1.24**. The caller allocates
// `VkDeviceMemory` *with `VkExportMemoryAllocateInfo`* (this must be decided up front — memory
// not allocated as exportable can never be imported), exports it to an OS handle with
// `vkGetMemoryWin32HandleKHR` (Windows) or `vkGetMemoryFdKHR` (Linux), and hands that handle to
// ORT. The EP re-imports it into its own `VkDeviceMemory` and wraps it as a zero-copy ORT tensor.
// Timeline-semaphore import for GPU↔GPU synchronisation rides along the same interface.
//
// # The symbols, precisely
//
// * EP side, ours to implement: `OrtEpFactory::CreateExternalResourceImporterForDevice`
//   (`\since Version 1.24`), returning an `OrtExternalResourceImporterImpl*`.
// * Caller side: `OrtInteropApi::CreateExternalResourceImporterForDevice`.
// * `CreateExternalResourceImporterForDeviceImpl` is **not** public API — it appears only as a
//   local static in ORT's example/test code. Do not go looking for it.
//
// The `OrtExternalResourceImporterImpl` vtable we would fill: `CanImportMemory`, `ImportMemory`,
// `ReleaseExternalMemoryHandle`, `CreateTensorFromMemory`, `CanImportSemaphore`,
// `ImportSemaphore`, `ReleaseExternalSemaphoreHandle`, `WaitSemaphore`, `SignalSemaphore`,
// `Release`. `OrtExternalMemoryHandle` and `OrtExternalSemaphoreHandle` are base structs the EP
// derives from by embedding them as the first field, the same `#[repr(C)]` trick used throughout
// this crate.
//
// # Reference implementation
//
// `onnxruntime/test/providers/nv_tensorrt_rtx/nv_vulkan_test.cc` in the ORT tree — the NV
// TensorRT RTX EP doing exactly our case, Vulkan on both sides. Match its contract rather than
// inventing our own; this is Vulkan-specific ORT support that already exists upstream.
//
// # Why it is not implemented now
//
// M0 runs everything on CPU with host-memory I/O. There is no device tensor to hand back yet, so
// an importer would have nothing to import into. The slot is left `None`, which ORT reads as
// "this EP cannot import external memory" — a legal, well-defined answer.
//
// # Why adding it later is additive, not a refactor
//
// One new `importer.rs` implementing the vtable, plus one gated line in `factory.rs`:
//
//     if negotiated.supports(sys::since::EXTERNAL_RESOURCE_IMPORTER) {
//         base.CreateExternalResourceImporterForDevice = Some(create_external_resource_importer);
//     }
//
// The gate is already meaningful: our minimum supported host is 1.24 and the API landed in 1.24,
// so it is exactly on the boundary. Nothing else in the crate moves — which is the point of
// keeping the whole ABI behind this module.
//
// # It does NOT answer OQ-3
//
// Evaluated and rejected as orthogonal; recorded in `.squad/decisions/inbox/tank-m0-foundation.md`
// so it does not get re-litigated. The importer answers "how does an external caller hand us
// *their* Vulkan buffer as a graph input or output" — and it is the complete answer to that.
// OQ-3 asks what our own `Alloc()` returns to ORT, whose allocator API is pointer-based, when a
// Vulkan allocation is a `VkBuffer` + offset. Different direction, different memory, different
// owner. That remains opaque-handle-registry vs `VK_KHR_buffer_device_address`, Tank to propose
// and Morpheus to decide.
// -------------------------------------------------------------------------------------------

/// Compile-time proof that the importer seam is present and correctly shaped in the bindings.
///
/// This is not decoration. The whole M0 claim about the importer is "the types are bound, the slot
/// exists, adding the implementation is additive" — if an ORT re-vendor renamed or removed any of
/// this, that claim would quietly stop being true and nobody would notice until someone tried to
/// implement it. Naming the items here turns that into a build failure at the moment of the bump.
///
/// It also pins the two Vulkan-specific handle-type enums, which are the values a future
/// `CanImportMemory` must accept: `VK_MEMORY_WIN32` on Windows, `VK_MEMORY_OPAQUE_FD` on Linux.
#[allow(dead_code)]
mod importer_seam {
    use super::ort;

    /// The EP-side vtable, ours to implement (see the TODO block above).
    pub type ImporterImpl = ort::OrtExternalResourceImporterImpl;
    /// The base struct an EP derives from for an imported memory handle.
    pub type MemoryHandle = ort::OrtExternalMemoryHandle;
    /// The base struct an EP derives from for an imported semaphore handle.
    pub type SemaphoreHandle = ort::OrtExternalSemaphoreHandle;
    /// Caller-side API, for reference — we never call this, applications do.
    pub type InteropApi = ort::OrtInteropApi;

    /// `vkGetMemoryWin32HandleKHR` handles.
    pub const HANDLE_TYPE_VK_MEMORY_WIN32: ort::OrtExternalMemoryHandleType =
        ort::OrtExternalMemoryHandleType_ORT_EXTERNAL_MEMORY_HANDLE_TYPE_VK_MEMORY_WIN32;
    /// `vkGetMemoryFdKHR` handles.
    pub const HANDLE_TYPE_VK_MEMORY_OPAQUE_FD: ort::OrtExternalMemoryHandleType =
        ort::OrtExternalMemoryHandleType_ORT_EXTERNAL_MEMORY_HANDLE_TYPE_VK_MEMORY_OPAQUE_FD;

    /// Timeline semaphores exported on Windows.
    pub const SEMAPHORE_TYPE_VK_TIMELINE_WIN32: ort::OrtExternalSemaphoreType =
        ort::OrtExternalSemaphoreType_ORT_EXTERNAL_SEMAPHORE_VK_TIMELINE_SEMAPHORE_WIN32;
    /// Timeline semaphores exported as an fd.
    pub const SEMAPHORE_TYPE_VK_TIMELINE_OPAQUE_FD: ort::OrtExternalSemaphoreType =
        ort::OrtExternalSemaphoreType_ORT_EXTERNAL_SEMAPHORE_VK_TIMELINE_SEMAPHORE_OPAQUE_FD;

    /// The Vulkan handle type this platform would export with.
    #[must_use]
    pub const fn native_vk_handle_type() -> ort::OrtExternalMemoryHandleType {
        if cfg!(windows) {
            HANDLE_TYPE_VK_MEMORY_WIN32
        } else {
            HANDLE_TYPE_VK_MEMORY_OPAQUE_FD
        }
    }
}

// -------------------------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// A `NegotiatedApi` with dangling pointers, for testing the pure version logic only.
    fn at_version(version: u32) -> NegotiatedApi {
        NegotiatedApi {
            api: std::ptr::null(),
            ep_api: std::ptr::null(),
            version,
        }
    }

    #[test]
    fn version_window_is_well_formed() {
        assert_eq!(ORT_API_VERSION_EXPECTED, 28, "we compile and ship against ORT 1.28");
        assert_eq!(ORT_API_VERSION_MIN, 24, "declared minimum supported host is ORT 1.24");
        // The ordering invariant is asserted at compile time at module scope; see the
        // `const _: () = assert!(ORT_API_VERSION_MIN <= ORT_API_VERSION_EXPECTED)` above.
        assert_eq!(ort::ORT_API_VERSION, ORT_API_VERSION_EXPECTED);
    }

    #[test]
    fn supports_is_a_real_gate_not_a_rubber_stamp() {
        // The point of the gate is that it says *no* to a downlevel host. A `supports` that only
        // ever returns true would pass every other test in this file.
        assert!(!at_version(23).supports(since::EXTERNAL_RESOURCE_IMPORTER));
        assert!(at_version(24).supports(since::EXTERNAL_RESOURCE_IMPORTER));
        assert!(at_version(28).supports(since::EXTERNAL_RESOURCE_IMPORTER));
    }

    #[test]
    fn every_since_constant_is_inside_the_supported_window() {
        // A `since::*` below the floor is dead weight (always true, so the gate is theatre); one
        // above what we compile against cannot be reached at all.
        for &(name, v) in since::ALL {
            assert!(
                v >= ORT_API_VERSION_MIN,
                "since::{name} = {v} is below the supported floor; the gate can never fail"
            );
            assert!(
                v <= ORT_API_VERSION_EXPECTED,
                "since::{name} = {v} is newer than the ABI we compile against"
            );
        }
    }

    #[test]
    fn external_resource_importer_landed_in_1_24() {
        // Verified against ORT's own `ort_version_supported < 24` guard in
        // `ep_factory_provider_bridge.h`. Justin's brief said 1.28; it is 1.24.
        assert_eq!(since::EXTERNAL_RESOURCE_IMPORTER, 24);
    }

    #[test]
    fn importer_seam_binds_the_vulkan_handle_types() {
        // Guards the M0 claim that the seam is bound and correctly shaped, so that adding the
        // implementation later is additive. If an ORT bump renames these, this fails.
        assert_ne!(
            importer_seam::HANDLE_TYPE_VK_MEMORY_WIN32,
            importer_seam::HANDLE_TYPE_VK_MEMORY_OPAQUE_FD
        );
        assert_ne!(
            importer_seam::SEMAPHORE_TYPE_VK_TIMELINE_WIN32,
            importer_seam::SEMAPHORE_TYPE_VK_TIMELINE_OPAQUE_FD
        );
        let native = importer_seam::native_vk_handle_type();
        if cfg!(windows) {
            assert_eq!(native, importer_seam::HANDLE_TYPE_VK_MEMORY_WIN32);
        } else {
            assert_eq!(native, importer_seam::HANDLE_TYPE_VK_MEMORY_OPAQUE_FD);
        }
    }

    #[test]
    fn null_api_base_is_rejected_without_dereferencing_it() {
        // SAFETY: passing null is exactly the case under test; the function null-checks first.
        let err = unsafe { check_api_version(std::ptr::null()) }.unwrap_err();
        assert!(err.contains("null OrtApiBase"), "{err}");
    }

    #[test]
    fn make_status_with_a_null_api_returns_null_rather_than_faulting() {
        // SAFETY: null is an explicitly supported argument.
        let s = unsafe { make_status(std::ptr::null(), ort::OrtErrorCode_ORT_EP_FAIL, "boom") };
        assert!(s.is_null());
    }

    #[test]
    fn releasing_a_status_with_null_arguments_is_a_noop() {
        // SAFETY: both null arguments are explicitly supported and short-circuit.
        unsafe { release_status(std::ptr::null(), std::ptr::null_mut()) };
    }
}
