#!/usr/bin/env python
"""Generate `evidence/proof_ledger.jsonl` — the §8.9 proof ledger. Owner: Mouse.

DESIGN.md §8.9.2 rule 3: *the ledger is generated by the differential harness, never
hand-edited.  It is emitted by the run that obtained the evidence, carries the device(s), the
ORT build, the tolerance policy applied and the artifact or builder the case came from, and is
baked into the cdylib at build time.*  This is that generator.

WHY THREE PASSES, AND WHY THE FIRST ONE EXISTS
----------------------------------------------
The gate is a chicken-and-egg by construction: with an empty ledger nothing is claimed, so no
differential run can obtain evidence about a claimed form.  §8.9.4 answers it — *"enabling a
form in order to prove it is the intended use"* — but you cannot enable a key you have no way
to learn.  So:

  pass 1  (discover)  run with the gate armed and `ONNXRUNTIME_EP_VULKAN_CLAIM_LOG` set.  Every
                      node records its `proof_key` whether it was claimed or not.  Collect the
                      keys of nodes whose ONLY decline was `[unproven]` — those are exactly the
                      forms that a proof would unlock and nothing else is wrong with.
  pass 2  (prove)     re-run with `ONNXRUNTIME_EP_VULKAN_CLAIM_UNPROVEN` set to those keys, and
                      compare every output against a CPU-only run of the same model.
  pass 3  (record)    write one entry per key IF AND ONLY IF the comparison returned MATCH.

A DIVERGENT run writes nothing — §8.9.2 rule 4 makes a divergent model verdict *demote* every
form that participated, and the mechanical form of "demote" in a generated file is "do not
emit".  There is no code path in this tool that can write an entry for a run that did not match.

WHAT THIS TOOL DOES NOT DO
--------------------------
It does not decide tolerance policy and it does not own the model-level verdict vocabulary.
Both belong to Trinity (`tests/ops/_verdict.py`); this tool reports the comparison it made and
records the policy it applied by name.  A second verdict vocabulary would be the R10 sub-rule
violation the census exists to catch.

USAGE
    python rust/tools/gen_proof_ledger.py --model model.onnx [--model other.onnx ...]
                                          [--device 0] [--out evidence/proof_ledger.jsonl]
                                          [--append]

    --check     verify an existing ledger instead of writing one (digest + duplicate keys +
                every entry's evidence artifact still present and unchanged).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import subprocess
import sys
import tempfile
import datetime

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
DEFAULT_OUT = REPO / "evidence" / "proof_ledger.jsonl"

# Must match `registry.rs::fnv1a64`.  A checksum, not a signature — see the doc comment there.
_FNV_OFFSET = 0xCBF29CE484222325
_FNV_PRIME = 0x00000100000001B3
_MASK = (1 << 64) - 1


def fnv1a64(data: bytes) -> int:
    h = _FNV_OFFSET
    for b in data:
        h ^= b
        h = (h * _FNV_PRIME) & _MASK
    return h


def _sha256(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# The child: one session, one model, in a subprocess.
#
# A subprocess because ONNXRUNTIME_EP_VULKAN_CLAIM_LOG and CLAIM_UNPROVEN are read when the EP
# DLL loads, and a parent that has already loaded onnxruntime cannot un-read them.  This is the
# same reason `test_wiring_census.py` shells out for its counters children.
# ---------------------------------------------------------------------------

_CHILD = "--proof-ledger-child"


def _child_main(spec_path: str) -> int:
    import numpy as np
    import onnxruntime as ort

    spec = json.loads(pathlib.Path(spec_path).read_text(encoding="utf-8"))
    model = spec["model"]
    use_ep = spec["use_ep"]

    so = ort.SessionOptions()
    so.log_severity_level = 2
    if use_ep and spec.get("strict_ep"):
        # ORT'S OWN REFUSAL, FROM OUTSIDE OUR CODE (added 2026-08-02).
        #
        # Every evidence case is a single-form model: either this EP claims the node or the
        # case proves nothing.  Our attribution is already counter-based (`claimed_nodes`,
        # `dispatches_executed`), but both of those counters are written by the thing being
        # audited.  This option is ORT refusing to build the session at all if any node lands
        # on the default CPU EP, so a run that would have compared CPU against CPU raises at
        # session creation instead of returning a `worst_rel` that has to be distrusted.
        #
        # It is deliberately *not* set on the discovery pass: discovery runs before the hatch
        # is open, the node is declined by design, and a refusal there is the expected state
        # rather than a finding.
        so.add_session_config_entry("session.disable_cpu_ep_fallback", "1")
    if use_ep:
        ep_lib = os.environ["ONNXRUNTIME_VULKAN_EP_LIB"]
        try:
            ort.register_execution_provider_library("VulkanExecutionProvider", ep_lib)
        except Exception as exc:  # already registered in this process is fine
            if "already" not in str(exc).lower():
                raise
        provs = ["VulkanExecutionProvider", "CPUExecutionProvider"]
        if spec.get("strict_ep"):
            # ORT rejects `disable_cpu_ep_fallback` outright when the CPU EP is *also* named
            # explicitly ("Conflicting session configuration"), which is an InvalidArgument at
            # session creation and reads nothing about our EP. The strict arm therefore offers
            # this EP alone; the CPU EP remains available to ORT as the default it is refusing
            # to fall back to.
            provs = ["VulkanExecutionProvider"]
        sess = ort.InferenceSession(model, so, providers=provs)
    else:
        sess = ort.InferenceSession(model, so, providers=["CPUExecutionProvider"])

    rng = np.random.default_rng(spec.get("seed", 20260801))

    # Some ops are partial functions. Feeding `standard_normal` to Sqrt produces NaN for roughly
    # half the elements on *both* EPs, and a case whose reference output is half NaN exercises
    # the kernel on half its elements while looking like a full case. `input_domain` names the
    # constraint the case model requires; the generator applies it rather than hoping the
    # distribution happens to stay inside it.
    domain = spec.get("input_domain", "any")

    def _floats(shape):
        v = rng.standard_normal(shape)
        if domain == "positive":
            return np.abs(v) + 0.5
        if domain == "nonzero":
            return np.where(np.abs(v) < 0.25, np.copysign(0.25, v), v)
        if domain == "unit":
            # |x| <= 0.9 — inside the domain of asin/acos and strictly inside atanh's, whose
            # value diverges at |x| = 1. `tanh` of a normal is a clean way to get there without
            # clipping, which would pile mass on the two endpoints and test them twice.
            return 0.9 * np.tanh(v)
        if domain == "ge_one":
            # acosh is real only for x >= 1.
            return 1.0 + np.abs(v)
        if domain == "discrete":
            # A small integer-valued set. `Equal` on two independent normals is all-False —
            # a constant reference, which proves nothing — so the comparison ops need inputs
            # that actually collide sometimes. Six values over two operands gives roughly one
            # element in six equal, which exercises both branches.
            return rng.integers(-3, 3, shape).astype(np.float64)
        if domain == "withnan":
            # `IsNaN` on a finite tensor is all-False, which is the same vacuous case. The
            # non-finite values are deliberate here and land in the *input*; the output is
            # boolean and stays finite, so this does not trip the non-finite-reference guard.
            v = v.copy()
            flat = v.reshape(-1)
            if flat.size >= 4:
                flat[0::4] = np.nan
                flat[1::4] = np.inf
            return v
        if domain == "withinf":
            # `IsInf`'s four predicates differ only on the sign of an infinity, so the input has
            # to carry both. NaN is here too because it is the value most likely to be confused
            # with an infinity by a shader that tested `x != x` or `abs(x) > large`.
            v = v.copy()
            flat = v.reshape(-1)
            if flat.size >= 4:
                flat[0::4] = np.inf
                flat[1::4] = -np.inf
                flat[2::4] = np.nan
            return v
        if domain == "spread":
            # A wider float draw, for ops whose interesting behaviour is at magnitudes a unit
            # normal rarely reaches — `Cast` to an integer, whose truncation is a no-op on almost
            # every element of a standard normal.
            return 100.0 * v
        return v

    def _ints(shape, dtype):
        """Integer feeds, domain-aware.

        The default `[0, 2)` is right for indices and masks and wrong for bitwise ops: a
        `BitwiseAnd` fed zeros and ones exercises **one bit of thirty-two**, and a shader that
        got the other thirty-one wrong would pass. `bits` draws full width.
        """
        if domain == "bits":
            info = np.iinfo(dtype)
            return rng.integers(info.min, info.max, shape, dtype=np.int64).astype(dtype)
        if domain == "spread":
            # Wide enough that the value matters, narrow enough that every value is exactly
            # representable in f32 — the `i32 -> f32` case must not turn on the rounding mode of
            # an integer-to-float conversion, which is a different question from whether the cast
            # is wired up.
            return rng.integers(-100_000, 100_000, shape).astype(dtype)
        return rng.integers(0, 2, shape).astype(dtype)

    feeds = {}
    plan = spec.get("feed_plan") or {}
    symbolic = plan.get("symbolic_dims") or {}
    fixed = plan.get("fixed_inputs") or {}
    scale = float(plan.get("float_scale", 1.0))
    for inp in sess.get_inputs():
        shape = [
            d if isinstance(d, int) and d > 0 else symbolic.get(d, 2) if isinstance(d, str) else 2
            for d in inp.shape
        ]
        dt = inp.type
        if inp.name in fixed:
            f = fixed[inp.name]
            feeds[inp.name] = np.asarray(f["values"], dtype=np.dtype(f["dtype"])).reshape(
                f["shape"]
            )
            continue
        if "float16" in dt:
            feeds[inp.name] = (_floats(shape) * scale).astype(np.float16)
        elif "float" in dt or "double" in dt:
            feeds[inp.name] = (_floats(shape) * scale).astype(np.float32)
        elif "int64" in dt:
            feeds[inp.name] = _ints(shape, np.int64)
        elif "int32" in dt:
            feeds[inp.name] = _ints(shape, np.int32)
        elif "uint8" in dt:
            feeds[inp.name] = rng.integers(0, 4, shape).astype(np.uint8)
        elif "bool" in dt:
            feeds[inp.name] = rng.integers(0, 2, shape).astype(bool)
        else:
            feeds[inp.name] = _floats(shape).astype(np.float32)

    outs = sess.run(None, feeds)
    np.savez(spec["outputs"], **{f"o{i}": o for i, o in enumerate(outs)})
    return 0


# ---------------------------------------------------------------------------
# Passes
# ---------------------------------------------------------------------------



ATTEMPTS = REPO / "evidence" / "proof_attempts.jsonl"


def _record_attempt(model_path, keys, verdict, detail, device, ort_build, tolerance, when):
    """Append every proof attempt, including the ones that prove nothing.

    A form that stays unproven after an honest attempt and a form nobody has attempted are two
    different states, and only one of them is a finding. The ledger cannot hold the difference:
    a non-MATCH line in `proof_ledger.jsonl` populates `Ledger::faults`, and a ledger with
    faults refuses every claim, not just the bad one. So the record goes beside it.

    This file grants nothing and is not baked into the binary. It exists so "we measured GQA
    and it disagreed by 16.7x" cannot decay into "GQA has no entry".
    """
    ATTEMPTS.parent.mkdir(parents=True, exist_ok=True)
    with ATTEMPTS.open("a", encoding="utf-8") as fh:
        fh.write(
            json.dumps(
                {
                    "case": model_path.name,
                    "keys": list(keys),
                    "verdict": verdict,
                    "detail": detail,
                    "device": device,
                    "ort_build": ort_build,
                    "tolerance": tolerance,
                    "attempted_at": when,
                },
                sort_keys=True,
            )
            + "\n"
        )


def _planted_control_key() -> str:
    """The key the ledger must never contain.

    Imported rather than duplicated: two copies of a constant is how the control gets disarmed
    on one side and left armed on the other.
    """
    try:
        import ledger_case_models
    except ImportError:
        return ""
    return getattr(ledger_case_models, "PLANTED_CONTROL_KEY", "")


def _domain_for(model: str) -> str:
    """The input sampling domain declared by the case model, keyed by file stem.

    Both arms must sample identically, so this is resolved once from the model path and passed
    to every child rather than being set per-arm.
    """
    try:
        import ledger_case_models
    except ImportError:
        return "any"
    return ledger_case_models.input_domain(pathlib.Path(model).stem)


def _feed_plan_for(model: str) -> dict:
    """Per-case overrides for inputs a random sampler cannot produce.

    Some forms have inputs that are not free variables: `GroupQueryAttention`'s
    `total_sequence_length` must equal past + current, and `seqlens_k` must agree with the KV
    cache extent. A random int32 there is not a harsher test, it is an invalid model — the CPU
    arm raises and the run reports ERROR(instrument) rather than a verdict.

    The plan is declared beside the case model, not here, for the same reason `input_domain`
    is: the next case would otherwise have to rediscover it in the runner.
    """
    try:
        import ledger_case_models
    except ImportError:
        return {}
    return ledger_case_models.feed_plan(pathlib.Path(model).stem)


def _run_child(
    model: str, use_ep: bool, env_extra: dict, outputs: pathlib.Path, strict_ep: bool = False
) -> None:
    with tempfile.TemporaryDirectory(dir=str(REPO / "bench" / "results")) as td:
        spec = pathlib.Path(td) / "spec.json"
        spec.write_text(
            json.dumps(
                {
                    "model": model,
                    "use_ep": use_ep,
                    "strict_ep": strict_ep,
                    "outputs": str(outputs),
                    "input_domain": _domain_for(model),
                    "feed_plan": _feed_plan_for(model),
                }
            ),
            encoding="utf-8",
        )
        env = dict(os.environ)
        env.update(env_extra)
        r = subprocess.run(
            [sys.executable, str(pathlib.Path(__file__).resolve()), _CHILD, str(spec)],
            env=env,
            capture_output=True,
            text=True,
            # The EP writes "§8.9.7" to its log sink. `text=True` alone decodes with the
            # platform default (cp1252 here), the decode raises inside subprocess's reader
            # *thread*, and the exception does not propagate — so `r.stderr` comes back empty
            # and a failing child's diagnostics are lost exactly when they are needed. R13: an
            # instrument that cannot report its own failure text turns FAIL into a mystery.
            encoding="utf-8",
            errors="replace",
            timeout=1800,
        )
        if r.returncode != 0:
            blob = f"{r.stdout}\n{r.stderr}"
            if _CPU_FALLBACK_REFUSAL in blob:
                # Not an instrument failure: ORT reached a conclusion about our EP and stated
                # it. Quote the text (R13) and let the caller record it as UNATTRIBUTED.
                raise CpuFallbackRefusal(
                    f"ORT refused the session for {model} because a node was assigned to the "
                    f"default CPU EP:\n{blob[-2000:]}"
                )
            # R13: an instrument failure is not a detection.  Raise, never return "no keys".
            raise InstrumentError(
                f"proof-ledger child failed (exit {r.returncode}) on {model}\n"
                f"--- stdout ---\n{r.stdout[-4000:]}\n--- stderr ---\n{r.stderr[-4000:]}"
            )


# ORT's own wording, observed verbatim on this build — not a string we wrote. Switch's finding of
# 2026-08-02 applies directly: *a classifier tested only against strings we wrote ourselves is
# tested against the one input it cannot get wrong*. His device-loss classifier matched
# `"device was lost"` and `"device_lost"` while the driver says `"The logical device has been
# lost"`, and fell through to the wrong class.
#
# This one is audited against that lesson and fails in the safe direction: if ORT rewords the
# message, the match misses and the run becomes `InstrumentError` — a raise, never a decline and
# never a proof. The dangerous version of this classifier would be one whose miss produced a
# verdict; this one's miss produces an error, so a reword costs a red lane, not a false entry.
_CPU_FALLBACK_REFUSAL = "fallback to CPU EP has been explicitly disabled"


class InstrumentError(RuntimeError):
    """The generator could not reach an observation.  Never a proof, never a decline."""


class CpuFallbackRefusal(RuntimeError):
    """ORT declined to build a session because a node fell to the default CPU EP.

    This is a *reading*, not an outage: it says the EP did not take the node, which for a
    single-form evidence case is exactly the vacuous-comparison state the ledger exists to
    exclude.  It is raised separately from `InstrumentError` so the two are never conflated.
    """


def discover_keys(model: str, reprove: bool = False) -> tuple[list[str], dict]:
    """Pass 1 — which forms would a proof unlock, and what else is wrong with them.

    With `reprove=True`, forms the EP **already claims** are returned as well.  Without it the
    generator can only ever measure forms that are not yet proven, which means a proven form is
    never re-measured and its entry silently outlives the kernel it describes (§8.9.11).  The
    skip is an optimisation; treating it as a policy is how a proof stops being about anything.
    """
    log = REPO / "bench" / "results" / "_ledger_claimlog.jsonl"
    if log.exists():
        log.unlink()
    outputs = REPO / "bench" / "results" / "_ledger_discover.npz"
    _run_child(model, True, {"ONNXRUNTIME_EP_VULKAN_CLAIM_LOG": str(log)}, outputs)
    if not log.is_file():
        # R13: the instrument produced no record. That is ERROR(instrument), never "no keys" —
        # "no keys" and "the claim log never opened" would otherwise be the same reading, and one
        # of them silently writes an empty ledger that certifies nothing.
        raise InstrumentError(
            f"claim log {log} was never written on {model}; the EP did not reach "
            f"claim_decision (did ORT fall back before GetCapability?)"
        )

    unlockable: list[str] = []
    census = {
        "records": 0, "unproven_only": 0, "other_decline": 0, "claimed": 0, "no_key": 0,
        "claimed_reoffered": 0,
    }
    for line in log.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        census["records"] += 1
        key = rec.get("proof_key")
        if not key:
            census["no_key"] += 1
            continue
        if rec.get("claimed"):
            census["claimed"] += 1
            if reprove and key not in unlockable:
                census["claimed_reoffered"] += 1
                unlockable.append(key)
            continue
        codes = set(rec.get("codes") or [])
        if codes == {"unproven"}:
            census["unproven_only"] += 1
            if key not in unlockable:
                unlockable.append(key)
        else:
            census["other_decline"] += 1
    return unlockable, census


def prove(model: str, keys: list[str], tolerance: tuple[float, float]) -> tuple[str, dict]:
    """Passes 2 and 3 — run both arms and compare.  Returns (verdict, detail).

    ATTRIBUTION IS PART OF THE VERDICT, NOT A NICETY.
    -------------------------------------------------
    Criterion 10 was closed on 2026-07-30 by a `MATCH` obtained from a run in which ORT had
    already fallen back to CPU — this EP executed zero nodes, so the verdict was `UNATTRIBUTED`,
    not `MATCH`, and the closure had to be withdrawn.  A ledger built the same way would be a
    file full of proofs that the CPU EP is correct.  So pass 2 also takes the EP's own counters
    and refuses to call anything MATCH unless the EP claimed nodes AND executed dispatches.
    `UNATTRIBUTED` is its own verdict and writes no entries.
    """
    import numpy as np

    if not keys:
        return "UNMEASURED", {"reason": "no unlockable keys on this model"}

    ep_out = REPO / "bench" / "results" / "_ledger_ep.npz"
    cpu_out = REPO / "bench" / "results" / "_ledger_cpu.npz"
    counters = REPO / "bench" / "results" / "_ledger_counters.json"
    if counters.exists():
        counters.unlink()
    try:
        _run_child(
            model,
            True,
            {
                "ONNXRUNTIME_EP_VULKAN_CLAIM_UNPROVEN": ";".join(keys),
                "ONNXRUNTIME_EP_VULKAN_COUNTERS_FILE": str(counters),
            },
            ep_out,
            strict_ep=True,
        )
    except CpuFallbackRefusal as exc:
        return "UNATTRIBUTED", {
            "reason": "ORT refused to build the session because a node was assigned to the "
            "default CPU EP; the comparison this run would have produced was CPU against CPU",
            "ort_refusal": str(exc)[-1200:],
            "offered": sorted(keys),
        }
    _run_child(model, False, {}, cpu_out)

    if not counters.is_file():
        raise InstrumentError(
            f"no counters file was written for {model}; attribution is unknowable, which is "
            f"ERROR(instrument) and not a verdict"
        )
    c = json.loads(counters.read_text(encoding="utf-8"))
    claimed = c.get("claimed_nodes", 0)
    dispatches = c.get("dispatches_executed", 0)
    hatch = c.get("unproven_forms_enabled", [])
    reproof = c.get("reproof_forms_admitted", [])
    admitted_keys = list(dict.fromkeys(list(hatch) + list(reproof)))
    if not claimed or not dispatches:
        return "UNATTRIBUTED", {
            "reason": "the EP claimed or executed nothing; a match against CPU proves nothing "
            "about a kernel that never ran",
            "claimed_nodes": claimed,
            "dispatches_executed": dispatches,
        }
    # ATTRIBUTION IS PER KEY, NOT PER RUN (revised 2026-08-02).
    #
    # The rule was `admitted == offered`, and it refused three legitimate proofs — `gelu_f16`,
    # `hardswish_f32`, `mish_f32`. The cause is not a defect in the EP: ORT calls `GetCapability`
    # on **more than one form of the graph** (`gelu_f16` produced 19 claim-log records for a
    # one-node model), so discovery sees keys belonging to graph states that the run that
    # actually executes does not contain. Requiring set equality made those models unprovable and
    # would have made every composite op unprovable forever.
    #
    # The replacement is stronger, not weaker, and it is stronger in the direction that matters:
    #
    #   * `admitted` must be **non-empty** — nothing used, nothing proven;
    #   * `admitted` must be a **subset** of `offered` — a key the run claimed under that nobody
    #     offered means the harness does not know what it ran, which is worse than a miss;
    #   * and the caller writes entries **only for the admitted keys**.
    #
    # Under the old rule a model offering two keys and using one wrote *two* entries whenever the
    # sets happened to match; under this one an entry can only exist for a key the run actually
    # claimed under. The number of entries a run can produce is now bounded by what it used
    # rather than by what it intended.
    if not admitted_keys:
        return "UNATTRIBUTED", {
            "reason": "the run admitted no unproven form; nothing was claimed under any offered "
            "key, so no key was exercised",
            "offered": sorted(keys),
        }
    unoffered = sorted(set(admitted_keys) - set(keys))
    if unoffered:
        return "UNATTRIBUTED", {
            "reason": "the run claimed under a key that was never offered; the harness cannot "
            "say what it ran",
            "offered": sorted(keys),
            "admitted": sorted(admitted_keys),
            "unoffered": unoffered,
        }

    a = np.load(str(ep_out))
    b = np.load(str(cpu_out))
    rtol, atol = tolerance
    worst = 0.0
    degenerate = []
    for name in a.files:
        x, y = a[name].astype("float64"), b[name].astype("float64")
        if x.shape != y.shape:
            return "DIVERGENT", {"reason": f"shape mismatch on {name}: {x.shape} vs {y.shape}"}

        # R13, and the seventh instance of this project's oldest failure mode.
        #
        # A **constant** CPU reference makes the comparison vacuous: two constant tensors agree
        # to any tolerance, so the run reports `MATCH` with `worst_rel 0.0` while having tested
        # nothing. This guard did not exist while the ledger held only arithmetic ops, whose
        # references vary by construction. It is added here because the batch that follows is
        # twelve **boolean-output** ops, where degeneracy is the default rather than the
        # accident: `Equal` on two independent normals is all-False, and so is `IsNaN`. Without
        # this, the cheapest way to "prove" twelve ops would have been to prove none of them.
        #
        # It is ERROR(instrument), not DIVERGENT: the kernel has not been shown wrong, the case
        # model has been shown inadequate. ERROR neither proves nor demotes — repair, re-run.
        if y.size > 1 and np.all(y == y.flat[0]):
            degenerate.append(name)
    if degenerate:
        return "ERROR", {
            "reason": (
                f"CPU reference output(s) {sorted(degenerate)} are constant, so the comparison "
                f"over them is vacuous: two constant tensors agree to any tolerance. The case "
                f"model does not exercise this op — repair its input domain and re-run"
            ),
            "instrument": "case_model_degenerate_reference",
        }
    for name in a.files:
        x, y = a[name].astype("float64"), b[name].astype("float64")
        if x.shape != y.shape:
            return "DIVERGENT", {"reason": f"shape mismatch on {name}: {x.shape} vs {y.shape}"}

        # R13 — an instrument error is never a detection.
        #
        # A non-finite value in the *reference* output means the case model drove the op outside
        # its domain (Sqrt of a negative, Log of a zero). Both EPs then agree on NaN, but
        # `np.allclose` reports NaN != NaN as divergence while `max(0.0, nan)` returns 0.0 — so
        # the verdict reads `DIVERGENT` with `worst_rel: 0.0`, a divergence of size zero. That
        # self-contradiction is the instrument describing itself, not the kernel. It is reported
        # as ERROR, and ERROR neither proves nor demotes: the case is repaired, then re-run.
        nonfinite_ref = int((~np.isfinite(y)).sum())
        if nonfinite_ref:
            return "ERROR", {
                "reason": (
                    f"output {name} contains {nonfinite_ref} non-finite value(s) in the CPU "
                    f"reference; the case model drove the op outside its domain, so this run "
                    f"compares NaN against NaN and can neither prove nor demote"
                ),
                "instrument": "case_model_input_domain",
            }
        nonfinite_ep = int((~np.isfinite(x)).sum())
        if nonfinite_ep:
            # Reference finite, EP non-finite: this one *is* a detection.
            return "DIVERGENT", {
                "reason": (
                    f"output {name} has {nonfinite_ep} non-finite value(s) where the CPU "
                    f"reference is finite everywhere"
                ),
            }

        denom = np.maximum(np.abs(y), 1e-30)
        rel = np.abs(x - y) / denom
        worst = max(worst, float(rel.max()) if rel.size else 0.0)
        if not np.allclose(x, y, rtol=rtol, atol=atol):
            return "DIVERGENT", {"reason": f"output {name} outside tolerance", "worst_rel": worst}
    return "MATCH", {
        "worst_rel": worst,
        "claimed_nodes": claimed,
        "dispatches_executed": dispatches,
        # §8.9.11 subject witness — which embedded SPIR-V modules this run bound, and their
        # digest, both taken from the EP's own dispatch record rather than re-derived here.
        "shaders_dispatched": c.get("shaders_dispatched", []),
        "shaders_dispatched_digest": c.get("shaders_dispatched_digest", ""),
        # §8.9.14 input witness — how many inferences this measurement is made of. One is what
        # makes the entry immune to input-cache staleness; the entry records the number so a
        # future multi-inference case cannot inherit that immunity by looking the same.
        "compute_calls": c.get("compute_calls"),
        # The keys this run actually claimed under — through the escape hatch (unproven forms) or
        # through the ledger while being deliberately re-offered (`--reprove`). Entries are
        # written for these and no others.
        "admitted": sorted(admitted_keys),
        "admitted_via_hatch": sorted(hatch),
        "admitted_via_reproof": sorted(reproof),
        # DEVICE IDENTITY, READ OFF THE RUN (added 2026-08-02, Mouse).
        #
        # `--device N` is a *selector ordinal*: a request handed to the loader, not a name for
        # hardware. Trinity's census shows `DEVICE=0` running on `1=NVIDIA`, so an entry stamped
        # `device0` names nothing a second run can be compared against. This is the name the EP
        # reports for the device it actually opened.
        "running_device_names": c.get("running_device_names", ""),
    }


# ---------------------------------------------------------------------------
# Writing and checking
# ---------------------------------------------------------------------------


def entry_line(key: str, device: str, ort_build: str, tolerance: str, artifact: str,
               artifact_sha256: str, generated_at: str, proof_run: dict) -> str:
    """One ledger entry, carrying the witnesses that a **proof run** produced it.

    RAI-008(a) discharge condition, provenance half.  The cheapest way to satisfy criterion 11 is
    to derive the ledger from the same enumeration that produces the claims: then
    `ledger_hits == proven_key_lookups` forever, the check can never fail, and `6/6` looks
    identical under both readings.  That is an identity whose two sides come from one source.

    The defence is not a promise in a doc comment, it is a field the claim table **cannot
    produce**.  `dispatches_executed` and `claimed_nodes` come from the EP's own execution
    counters after a session ran; `executed_by` comes from ORT's profile, an instrument this
    project does not own.  A ledger enumerated from the registry table would have to fabricate
    all three, and `registry.rs::parse_ledger` faults any entry whose attribution is absent or
    zero — so a table-derived ledger grants no claims at all rather than granting them silently.
    """
    claimed = int(proof_run.get("claimed_nodes", 0))
    dispatches = int(proof_run.get("dispatches_executed", 0))
    compute_calls = proof_run.get("compute_calls")
    shaders = sorted(proof_run.get("shaders_dispatched") or [])
    shader_digest = proof_run.get("shaders_dispatched_digest") or ""
    # THE DEVICE FIELD MUST NAME HARDWARE, NOT A REQUEST (2026-08-02, Mouse).
    #
    # `device` as passed in is `device{N}` — the *selector ordinal*, which is what the caller
    # asked the loader for and not what the loader gave it. `DEVICE=0` has run on `1=NVIDIA` in
    # this very repo. An entry stamped with an ordinal cannot be compared against a second run's
    # hardware, so `registry::device_state` classifies it `DEVICE-UNATTRIBUTED` and says so.
    #
    # The name the EP reports for the device it opened is preferred whenever the run produced
    # one. The ordinal is kept beside it, under its own key, because it is still the thing to
    # pass to reproduce the run — it is simply not an identity.
    running = (proof_run.get("running_device_names") or "").strip()
    device_selector = device
    if running and running not in ("none", "unknown"):
        device = running
    if claimed <= 0 or dispatches <= 0:
        raise SystemExit(
            f"REFUSING to write an entry for {key}: attribution is "
            f"claimed_nodes={claimed} dispatches_executed={dispatches}. An entry with no "
            f"attribution witness did not come from a proof run."
        )
    # §8.9.14 — ONE INFERENCE PER ARM, AND IT HAS TO BE A FIELD, NOT A HABIT.
    #
    # Switch found on 2026-08-02 that the input cache was keyed on `(cpu_ptr, byte_size)` with a
    # 32 KiB floor and no content check, so every inference after the first in a session read the
    # first one's inputs. It is invisible to the shader digest — the shaders did not change — so
    # it is precisely the class of staleness §8.9.11's subject witness does NOT cover.
    #
    # Every entry in this ledger is safe from it for a structural reason: each arm is a fresh
    # subprocess that builds one session and calls `sess.run` exactly once, so there is no second
    # inference for a stale cache to serve. The counters agree — `compute_calls: 1`.
    #
    # That is a true statement about today's harness and a fragile one about tomorrow's. A future
    # case that needs two inferences (a KV-cache form, say) would silently reintroduce the
    # exposure, and the entry would look identical. So the count is recorded in the entry and a
    # run that computed more than once refuses to write one until somebody has decided what a
    # multi-inference proof means.
    if compute_calls is not None and int(compute_calls) > 1:
        raise SystemExit(
            f"REFUSING to write an entry for {key}: the proof run made "
            f"{compute_calls} Compute() calls. Single-inference arms are what makes an entry "
            f"immune to input-cache staleness, which no shader digest can detect. If this case "
            f"genuinely needs several inferences, say what its proof means first."
        )
    # §8.9.11 — SUBJECT PROVENANCE.  Attribution says a run happened; it says nothing about what
    # code ran.  An entry that cannot name its shader set cannot be invalidated when that shader
    # set is replaced, and on 2026-08-02 exactly that happened: the GQA entry survived two shader
    # rewrites because `--append` skipped re-measuring an already-claimed form.  A proof that
    # cannot be invalidated by changing its subject is not a proof of that subject.
    if not shaders or not shader_digest or shader_digest == "NONE-DISPATCHED":
        raise SystemExit(
            f"REFUSING to write an entry for {key}: the run reported shaders={shaders!r} "
            f"digest={shader_digest!r}. Without a subject witness the entry would outlive the "
            f"kernel it proves. This is an instrument gap, not a licence to write the entry."
        )
    return json.dumps(
        {
            "key": key,
            "verdict": "MATCH",
            "device": device,
            "device_selector": device_selector,
            "ort_build": ort_build,
            "tolerance": tolerance,
            "artifact": artifact,
            "artifact_sha256": artifact_sha256,
            "generated_at": generated_at,
            # --- provenance: written by a proof run, never by the claim table ---
            "claimed_nodes": claimed,
            "dispatches_executed": dispatches,
            # --- subject provenance: what code this proof is about (§8.9.11) ---
            "shaders": shaders,
            "shader_digest": shader_digest,
            # --- input provenance: how many inferences this proof is made of (§8.9.14) ---
            **({} if compute_calls is None else {"compute_calls": int(compute_calls)}),
            "worst_rel": float(proof_run.get("worst_rel", 0.0)),
        },
        separators=(",", ":"),
        sort_keys=True,
    )


def write_ledger(out: pathlib.Path, lines: list[str], *, allow_shrink: bool = False) -> int:
    """Write the ledger, refusing to shrink it unless told to. Returns an R13 exit code.

    A DESTRUCTIVE WRITE THAT REPORTS SUCCESS IS THE DEFECT THIS FILE KEEPS RE-LEARNING.
    ---------------------------------------------------------------------------------
    2026-08-02, twice in one day. First: `--append` was the only path that loaded existing
    entries, so a plain run rewrote the file with what that invocation proved and then printed
    `PASS`, because `--check` was asked whether the file it had just written was internally
    consistent — which an empty file is. Fixed by always carrying entries forward. Then Switch
    hit it again through `--reprove`, 74 entries to 1, `PASS`.

    Carrying forward makes a drop *unlikely*. It does not make it a **detection**, and the
    coordinator's instruction is the right one: an entry-count drop must be `FAIL(condition)`,
    not something a reader has to notice in a line of output. So the count is compared against
    what is on disk before the write happens, and a shrink refuses to write at all.

    `allow_shrink` is `--rebuild`, which has to be asked for by name.
    """
    before = 0
    before_keys: set[str] = set()
    if out.is_file():
        try:
            existing = [
                l for l in (x.strip() for x in out.read_text(encoding="utf-8").splitlines())
                if l and not l.startswith("#")
            ]
            before = max(len(existing) - 1, 0)
            for line in existing[1:]:
                try:
                    before_keys.add(json.loads(line)["key"])
                except (ValueError, KeyError):
                    pass
        except OSError as exc:
            print(f"ERROR(instrument): cannot read {out} to compare entry counts: {exc}")
            return 3
    if before and len(lines) < before and not allow_shrink:
        keeping: set[str] = set()
        for line in lines:
            try:
                keeping.add(json.loads(line)["key"])
            except (ValueError, KeyError):
                pass
        dropped = sorted(before_keys - keeping)
        shown = "\n".join(f"    - {k}" for k in dropped[:20])
        if len(dropped) > 20:
            shown += f"\n    ... and {len(dropped) - 20} more"
        print(
            f"FAIL(condition): refusing to write {out} — it holds {before} entr(ies) and this "
            f"run would leave {len(lines)}. Entries are evidence; losing them is not a "
            f"side effect of a successful run. Nothing was written. If the shrink is intended, "
            f"say so with --rebuild.\n"
            f"  would have dropped {len(dropped)} key(s):\n{shown}"
        )
        return 1
    body = "".join(line + "\n" for line in lines)
    header = json.dumps(
        {
            "__ledger__": 1,
            "generator": "rust/tools/gen_proof_ledger.py",
            "generator_version": "1",
            "generated_at": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
            "entry_count": len(lines),
            "content_fnv1a64": f"{fnv1a64(body.encode('utf-8')):016x}",
        },
        separators=(",", ":"),
        sort_keys=True,
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header + "\n" + body, encoding="utf-8")
    return 0


def check_ledger(path: pathlib.Path) -> int:
    """The regeneration check.  PASS / FAIL(condition) / ERROR(instrument), R13."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"ERROR(instrument): cannot read {path}: {exc}")
        return 3
    lines = [l for l in (x.strip() for x in text.splitlines()) if l and not l.startswith("#")]
    if not lines:
        print(f"ERROR(instrument): {path} is empty — a missing ledger is not an empty one")
        return 3
    header = json.loads(lines[0])
    body = "".join(l + "\n" for l in lines[1:])
    digest = f"{fnv1a64(body.encode('utf-8')):016x}"
    failures = []
    if header.get("content_fnv1a64") != digest:
        failures.append(
            f"digest mismatch: header declares {header.get('content_fnv1a64')}, "
            f"contents hash to {digest} — the ledger has been hand-edited"
        )
    if header.get("entry_count") != len(lines) - 1:
        failures.append(
            f"entry_count {header.get('entry_count')} != {len(lines) - 1} entries present"
        )
    seen = set()
    planted = _planted_control_key()
    for raw in lines[1:]:
        e = json.loads(raw)
        key = e.get("key", "")
        if planted and key == planted:
            # The control is only a control while it is unproven. A ledger containing it looks
            # exactly like a healthy ledger, and every test that depends on the control passes
            # for the wrong reason — this is the one failure the artifact cannot self-report.
            failures.append(
                f"entry {key} is the PLANTED CONTROL key; a proof of the control disarms the "
                f"only check that shows the gate declines anything at all"
            )
        if key in seen:
            failures.append(f"duplicate key {key}")
        seen.add(key)
        if e.get("verdict") != "MATCH":
            failures.append(f"entry {key} carries verdict {e.get('verdict')!r}; only MATCH proves")
        if "/" not in key or key in {"*", "1", "all", "true", "yes"}:
            failures.append(f"key {key!r} is not a valid full proof key")
        art = e.get("artifact", "")
        art_path = REPO / art if art and not pathlib.Path(art).is_absolute() else pathlib.Path(art)
        if not art:
            failures.append(f"entry {key} names no evidence artifact")
        elif not art_path.is_file():
            failures.append(f"entry {key} names evidence {art} which does not exist")
        elif _sha256(art_path) != e.get("artifact_sha256"):
            failures.append(f"entry {key} evidence {art} has changed since it was recorded")
        # RAI-008(a): provenance. These three cannot be produced by enumerating the claim table,
        # which is the cheapest-satisfaction failure mode Morpheus named. Absent or zero is the
        # same finding as fabricated, because a run that dispatched nothing proved nothing.
        for field in ("claimed_nodes", "dispatches_executed"):
            value = e.get(field)
            if not isinstance(value, int):
                failures.append(
                    f"entry {key} carries no {field}; it does not record a proof run and may "
                    f"have been enumerated rather than proven"
                )
            elif value <= 0:
                failures.append(
                    f"entry {key} has {field}={value}; a run that claimed or dispatched nothing "
                    f"is UNATTRIBUTED and proves nothing"
                )
        # §8.9.11: subject provenance. Shape is checked here; *agreement* with the shaders in the
        # build is checked in `registry.rs::parse_ledger`, which is the only place the compiled
        # SPIR-V exists. Splitting it that way is deliberate — a Python re-derivation of the
        # digest would be a second implementation of the thing being checked.
        shaders = e.get("shaders")
        digest_field = e.get("shader_digest")
        if not isinstance(shaders, list) or not shaders:
            failures.append(
                f"entry {key} names no shader set; it cannot say what code it proved, so no "
                f"change to that code can ever invalidate it"
            )
        if not isinstance(digest_field, str) or not digest_field or digest_field == "NONE-DISPATCHED":
            failures.append(
                f"entry {key} carries no shader digest ({digest_field!r}); the entry would "
                f"outlive its subject"
            )
    if failures:
        print(f"FAIL(condition=LEDGER_INVALID): {path}")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"PASS: {path} — {len(lines) - 1} entr(ies), digest {digest}")
    return 0


def main() -> int:
    if len(sys.argv) >= 3 and sys.argv[1] == _CHILD:
        return _child_main(sys.argv[2])

    ap = argparse.ArgumentParser()
    ap.add_argument("--model", action="append", default=[])
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--append", action="store_true")
    ap.add_argument(
        "--rebuild",
        action="store_true",
        help="DISCARD every existing entry and write only what this run proved. Without this "
        "the ledger is always carried forward: the default write used to be destructive and "
        "reported PASS over the file it had just emptied.",
    )
    ap.add_argument(
        "--reprove",
        action="store_true",
        help="re-measure forms that are ALREADY claimed and replace their entries. Without this "
             "the generator can only measure unproven forms, so an entry is never re-checked "
             "against the kernel it names and silently outlives it (§8.9.11).",
    )
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--rtol", type=float, default=1e-3)
    ap.add_argument("--atol", type=float, default=1e-5)
    ap.add_argument("--device", default=os.environ.get("ONNXRUNTIME_EP_VULKAN_DEVICE", "0"))
    ap.add_argument("--device-name", default="")
    args = ap.parse_args()

    out = pathlib.Path(args.out)
    if args.check:
        return check_ledger(out)

    if not args.model:
        ap.error("--model is required unless --check")

    os.environ["ONNXRUNTIME_EP_VULKAN_DEVICE"] = str(args.device)
    import onnxruntime as ort

    ort_build = ort.__version__
    device = args.device_name or f"device{args.device}"
    tolerance = f"rtol={args.rtol},atol={args.atol}"
    now = datetime.datetime.now().astimezone().isoformat(timespec="seconds")

    existing: list[str] = []
    if out.is_file():
        existing = [
            l for l in (x.strip() for x in out.read_text(encoding="utf-8").splitlines())
            if l and not l.startswith("#")
        ][1:]
    on_disk = {json.loads(l)["key"] for l in existing}
    # THE DEFAULT WRITE USED TO BE DESTRUCTIVE (fixed 2026-08-02, after it destroyed 95 entries).
    #
    # `existing` was loaded only under `--append`. Without it the generator rewrote the file with
    # nothing but what this invocation proved, so a single-model run reduced the ledger to that
    # model's entries — and then printed `PASS`, because `check_ledger` was asked whether the
    # file it had just written was internally consistent, which an empty file is. Two halves of a
    # report describing different things, exactly the §8.9.11 shape one level out.
    #
    # Entries are now always carried forward. Discarding them is `--rebuild`, which has to be
    # asked for, and `--append` is retained as a no-op alias so existing lanes keep working.
    if not args.append and not args.rebuild and existing:
        print(
            f"[carry]    {len(existing)} existing entr(ies) carried forward from {out.name}; "
            f"pass --rebuild to discard them deliberately"
        )
    if args.rebuild:
        print(f"[rebuild]  discarding {len(existing)} existing entr(ies) on request")
        existing = []
    have = set(on_disk) if not args.rebuild else set()

    planted = _planted_control_key()
    planted_case = getattr(
        __import__("ledger_case_models"), "PLANTED_CONTROL_CASE", "?"
    ) if planted else "?"

    new_lines = list(existing)
    measured_any = False
    reproved: list[str] = []
    for model in args.model:
        model_path = pathlib.Path(model).resolve()
        keys, census = discover_keys(str(model_path), reprove=args.reprove)
        print(f"[discover] {model_path.name}: {census}, {len(keys)} unlockable key(s)")
        for k in keys:
            print(f"    would decline without a proof: {k}")
        verdict, detail = prove(str(model_path), keys, (args.rtol, args.atol))
        print(f"[prove]    {model_path.name}: {verdict} {detail}")
        _record_attempt(model_path, keys, verdict, detail, device, ort_build, tolerance, now)
        if keys:
            measured_any = True
        else:
            # R13, and the same defect Scribe had in her health report: a run that measured
            # nothing must not contribute to a PASS. `--append` skips already-claimed forms, so
            # `UNMEASURED ... no unlockable keys` followed by `PASS` is a report whose two halves
            # describe different things — one of them the ledger's validity, the other a run that
            # did not happen.
            print(
                f"    NOT MEASURED: {model_path.name} offered no key to prove. If the form is "
                f"already claimed, this run re-checked nothing — use --reprove to re-measure it."
            )
        if verdict != "MATCH":
            print(f"    no entries written for {model_path.name} — only MATCH proves")
            continue
        sha = _sha256(model_path)
        try:
            rel = str(model_path.relative_to(REPO)).replace("\\", "/")
        except ValueError:
            rel = str(model_path).replace("\\", "/")
        # Only the admitted keys. A key that was discovered but never claimed under in the
        # proof run has no proof, however green the run looked.
        admitted = set(detail.get("admitted") or [])
        skipped = [k for k in keys if k not in admitted]
        if skipped:
            print(f"    discovered but not exercised by the proof run, so unproven: {skipped}")
        for k in keys:
            if k not in admitted:
                continue
            if k == planted:
                # 2026-08-02: the ledger acquired the planted control's form and disarmed the
                # only check that would have noticed. The generator refuses rather than warns —
                # a warning here is a line of output in a forty-minute run.
                raise SystemExit(
                    f"REFUSING to write an entry for the planted control key {k!r} "
                    f"(case {planted_case!r}). A proof of the control is the control switched "
                    f"off, and it is switched off silently. If this form genuinely needs to be "
                    f"claimable, MOVE the control first and say so, in "
                    f"rust/tools/ledger_case_models.py."
                )
            if k in have:
                if not args.reprove:
                    continue
                # Replace rather than append: two entries for one key is the fork R7 forbids, and
                # `parse_ledger` faults a duplicate. The new measurement wins because it is the
                # one taken against the shaders in this build.
                new_lines = [ln for ln in new_lines if json.loads(ln)["key"] != k]
                reproved.append(k)
            have.add(k)
            new_lines.append(
                entry_line(k, device, ort_build, tolerance, rel, sha, now, detail)
            )

    if reproved:
        print(f"[reprove]  replaced {len(reproved)} entr(ies) with fresh measurements")
    rc_write = write_ledger(out, new_lines, allow_shrink=args.rebuild)
    if rc_write != 0:
        # R13: the refusal is the terminal state. Do not run `--check` afterwards — it would be
        # asked about the file on disk, which is now the *old* one, and would answer `PASS`.
        # A report whose two halves describe different things is the defect, not the format.
        return rc_write
    print(f"[write]    {out}: {len(new_lines)} entr(ies)")
    rc = check_ledger(out)
    if rc == 0 and not measured_any:
        # The ledger is valid AND this run measured nothing. Both are true, and reporting only
        # the first is how `PASS` came to sit under `UNMEASURED`.
        print(
            "NOTE: the ledger is valid, but this run measured no form. That is a statement "
            "about the file, not about any kernel. Re-run with --reprove to measure."
        )
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
