"""Workload definitions for the CUDA-competition suite (issue #69). Owner: Niobe.

A workload is a *shape*, not a model.  The same shape must be presentable to
every arm — Vulkan EP, CUDA EP, CPU EP — as byte-identical input tensors, or the
arms are not running the same thing and their ratio is not a provider ratio.

Three families, matching what issue #69's success criterion actually needs:

``prefill``
    ``sequence_length`` in {1, 2, 4, 8, 16, 32, 64, 128}, empty KV cache.  This
    is the compute-bound end: at ``M`` = 128 the quantised matmuls are real GEMMs.

``decode``
    ``sequence_length`` = 1 with a **non-empty** KV cache at representative past
    lengths.  This is the memory-bound end and the one that determines
    tokens/second in a real chat loop.  A decode benchmark run with an *empty*
    cache measures a different kernel, so ``past_len`` = 0 is deliberately not a
    decode workload — it is ``prefill_1``.

``vision`` / ``encoder``
    Fixed-shape single-pass models (MobileNetV2, MiniLM), included because the
    LLM path alone cannot tell a general EP gap from a MatMulNBits gap.

Feeds are generated from an explicit seed with an explicit dtype per input, and
the generated bytes are digested.  The digest travels with the result, so a
reader can verify that the CUDA arm and the Vulkan arm were fed the same bytes
rather than take it on trust.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field

PREFILL_LENGTHS = (1, 2, 4, 8, 16, 32, 64, 128)
#: Past lengths for decode.  Chosen to straddle the KV-arena boundary characterised
#: on this hardware (Switch, 2026-08-04: the shipping host-KV lane's boundary is
#: 2560, not 4096), so the suite says something on both sides without assuming the
#: far side runs.
DECODE_PAST_LENGTHS = (128, 512, 1024, 2048)


@dataclass(frozen=True)
class Workload:
    key: str
    model_key: str
    family: str
    seq_len: int
    past_len: int
    batch: int = 1
    note: str = ""

    @property
    def total_len(self) -> int:
        return self.past_len + self.seq_len


def llm_workloads(model_key: str = "phi35_int4") -> "list[Workload]":
    out: "list[Workload]" = []
    for n in PREFILL_LENGTHS:
        out.append(Workload(
            key=f"prefill_{n}", model_key=model_key, family="prefill",
            seq_len=n, past_len=0,
            note="empty KV cache; M=n through every quantised matmul",
        ))
    for past in DECODE_PAST_LENGTHS:
        out.append(Workload(
            key=f"decode_past{past}", model_key=model_key, family="decode",
            seq_len=1, past_len=past,
            note="one new token against a populated KV cache — the shape a chat loop "
                 "spends almost all of its time in",
        ))
    return out


def vision_workloads(model_key: str = "mobilenetv2_12") -> "list[Workload]":
    return [Workload(key="mobilenetv2_b1", model_key=model_key, family="vision",
                     seq_len=1, past_len=0, batch=1,
                     note="224x224x3 float32, batch 1")]


def encoder_workloads(model_key: str = "all_minilm_l6_v2") -> "list[Workload]":
    return [Workload(key=f"minilm_seq{n}", model_key=model_key, family="encoder",
                     seq_len=n, past_len=0, batch=1,
                     note="BERT-family encoder, single pass, no cache")
            for n in (16, 64, 128)]


def all_workloads() -> "list[Workload]":
    return llm_workloads() + vision_workloads() + encoder_workloads()


# ---------------------------------------------------------------------------
# Feed construction
# ---------------------------------------------------------------------------

@dataclass
class Feeds:
    arrays: dict = field(default_factory=dict)
    digest: str = ""
    total_bytes: int = 0
    shapes: dict = field(default_factory=dict)


def _digest_arrays(arrays: dict) -> "tuple[str, int, dict]":
    """Digest the exact bytes fed to the session, plus name/dtype/shape.

    Digesting the buffer alone would call an int64 ``[1,4]`` and an int32 ``[2,2]``
    with the same contents the same feed.  Name and dtype are part of the input.
    """
    h = hashlib.sha256()
    total = 0
    shapes = {}
    for name in sorted(arrays):
        arr = arrays[name]
        h.update(name.encode("utf-8"))
        h.update(b"\0")
        h.update(str(arr.dtype).encode("ascii"))
        h.update(b"\0")
        h.update(str(arr.shape).encode("ascii"))
        h.update(b"\0")
        buf = arr.tobytes()
        h.update(buf)
        total += len(buf)
        shapes[name] = [str(arr.dtype), list(arr.shape)]
    return h.hexdigest(), total, shapes


def build_feeds(session, workload: Workload, *, seed: int = 20260807) -> Feeds:
    """Build byte-identical feeds for ``workload`` against ``session``'s signature.

    Driven off the session's declared inputs rather than a hardcoded name list, so
    the same function serves the Phi-3.5 66-input KV graph, MobileNetV2 and MiniLM.
    Symbolic dimensions are bound from the workload; any remaining free dimension is
    an error rather than a guess, because a guessed dimension silently changes the
    amount of work the arm does.
    """
    import numpy as np

    rng = np.random.default_rng(seed)
    arrays: dict = {}

    dtype_map = {
        "tensor(float)": np.float32,
        "tensor(float16)": np.float16,
        "tensor(int64)": np.int64,
        "tensor(int32)": np.int32,
        "tensor(uint8)": np.uint8,
        "tensor(bool)": np.bool_,
    }

    for meta in session.get_inputs():
        np_dtype = dtype_map.get(meta.type)
        if np_dtype is None:
            raise ValueError(f"input {meta.name!r} has unsupported type {meta.type!r}")

        dims: "list[int]" = []
        for d in meta.shape:
            if isinstance(d, int):
                dims.append(d)
                continue
            token = str(d)
            if token in ("batch_size", "batch", "N"):
                dims.append(workload.batch)
            elif token in ("sequence_length", "seq_len", "sequence"):
                dims.append(workload.seq_len)
            elif token in ("past_sequence_length", "past_seq_len"):
                dims.append(workload.past_len)
            elif token in ("total_sequence_length", "total_seq_len"):
                dims.append(workload.total_len)
            elif token in ("height", "width"):
                dims.append(224)
            elif token in ("channels", "num_channels"):
                dims.append(3)
            else:
                raise ValueError(
                    f"input {meta.name!r} has an unbound symbolic dimension {token!r}; "
                    f"this harness refuses to guess a dimension because a guess silently "
                    f"changes how much work the arm does")

        if np_dtype in (np.int64, np.int32):
            if meta.name == "attention_mask":
                arr = np.ones(dims, dtype=np_dtype)
            elif meta.name in ("token_type_ids",):
                arr = np.zeros(dims, dtype=np_dtype)
            elif meta.name == "position_ids":
                arr = np.arange(workload.past_len, workload.total_len,
                                dtype=np_dtype).reshape(dims)
            else:
                # Vocabulary-safe token ids: 1000..1999 is inside every vocabulary in
                # this suite and avoids special tokens whose embeddings are degenerate.
                arr = rng.integers(1000, 2000, size=dims, dtype=np.int64).astype(np_dtype)
        elif np_dtype is np.bool_:
            arr = np.ones(dims, dtype=np.bool_)
        elif np_dtype is np.uint8:
            arr = rng.integers(0, 256, size=dims, dtype=np.uint8)
        else:
            # Small-amplitude activations: fp16 accumulation over a 3072-wide hidden
            # state overflows on N(0,1) inputs, and an overflow makes every arm agree
            # on `inf` — a correctness check that passes because both sides are broken.
            arr = (rng.standard_normal(dims) * 0.05).astype(np_dtype)

        if 0 in dims:
            arr = np.zeros(dims, dtype=np_dtype)
        arrays[meta.name] = np.ascontiguousarray(arr)

    digest, total, shapes = _digest_arrays(arrays)
    return Feeds(arrays=arrays, digest=digest, total_bytes=total, shapes=shapes)
